copyup:
	#python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker test.asm test.asm
	#python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker test2.asm test2.asm
	python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker macros.inc macros.inc
	python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker print.inc print.inc
	python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker file.inc file.inc
	python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker forth.asm forth.asm
	python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker params.asm params.asm
	python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker hexdump.asm hexdump.asm
