copyup:
	#python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker test.asm test.asm
	#python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker test2.asm test2.asm
	python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker forth.asm forth.asm
	python ../../ctostool/ctostool.py ../../converted/img/DSKA0264-incoming-aws2.img replace baker params.asm params.asm
